.TH tumgreyspf 8

.SH NAME
tumgreyspf \- an external policy checker for the postfix mail server

.SH SYNOPSIS
.B tumgreyspf
[
.I configfilename
]

.SH DESCRIPTION

Tumgreyspf can optionally greylist and/or use spfquery to check SPF records
to determine if email should be accepted by your server.

SPF is information published by the domain owner about what systems may
legitimately send e-mail for the domain.  Greylisting takes advantage
of spam and viruses that do not follow the RFCs and retry deliveries on
temporary failure.  We use these checks as part of our mail system and
have seen several orders of magnitude reduction in spam, lower system
load, and few problems with legitimate mail getting blocked.

Tumgreyspf uses the file-system as it's database, no additional database is
required to use it.

This man page is a place holder for whoever wants to write a doc to this. Feel
free to send it to the upstream Sean Reifschneider <jafo@tummy.com> or to me,
the Debian maintainer, Thomas Goirand <thomas@goirand.fr>.

.SH "SEE ALSO"

Homepage: <http://www.tummy.com/Community/software/tumgreyspf/>
